name: Run flutter tests
on:
  workflow_call:
    inputs:
      app-dir:
        required: true
        type: string
      app-path:
        required: true
        type: string
      environment: # options development|staging|production
        required: true
        type: string

    secrets:
      ios_provisioning_profile_password:
        required: true
      ios_provisioning_profile_asc:
        required: true
      ios_certificate_asc:
        required: true
      ios_certificate_password:
        required: true
      app_store_api_private_key:
        required: true
      app_store_issuer_id:
        required: true
      app_store_api_key_id:
        required: true
      p12_password:
        required: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      # Checkout the current GitHub repository.
      - uses: actions/checkout@v2
      
      # Install the correct Flutter version on the build agent.
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Download and install the Melos Dart package.
      - name: Download melos
        run: flutter pub global activate melos

      # Bootstrap Melos and download Flutter dependencies required by the project.
      - name: Install Dependencies
        run: melos bootstrap && melos get
        working-directory: ${{env.app-dir}}

      # Validate if the source code is formatted according to the Dart style guide (https://github.com/dart-lang/dart_style/wiki/Formatting-Rules).
      - name: Format
        run: melos format:set_exit_if_changed
        working-directory: ${{env.app-dir}}

      # Validate the source code against the configured linting rules (see `analysis_options.yaml`).
      - name: Analyze
        run: melos analyze
        working-directory: ${{env.app-dir}}

      # Runs all unit-tests that are part of the Flutter project.
      - name: Run tests
        run: melos test
        working-directory: ${{env.app-dir}}

      # Install the Apple signing certificate and provisioning profiles on the build agent.
      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.ios_signing_key_asc }}
          P12_PASSWORD: ${{ secrets.p12_password }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.ios_provisioning_profile_asc }}
          KEYCHAIN_PASSWORD: ${{ secrets.ios_keychain_password }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/distribution.p12
          PP_PATH=$RUNNER_TEMP/provisioningprofile.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          RANDOM_KEYCHAIN_PASSWORD="$(openssl rand -hex 100)"

          # decrypt the provisioning profile and signing certificate
          echo "${{secrets.ios_provisioning_profile_asc}}" > provisioningprofile.mobileprovision.asc
          gpg -d --passphrase "${{ secrets.ios_provisioning_profile_password }}" --batch provisioningprofile.mobileprovision.asc > $PP_PATH
          echo "${{secrets.ios_certificate_asc}}" > distribution.p12.asc
          gpg -d --passphrase "${{ secrets.ios_certificate_password }}" --batch distribution.p12.asc > $CERTIFICATE_PATH

          # create temporary keychain
          security create-keychain -p $RANDOM_KEYCHAIN_PASSWORD $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p $RANDOM_KEYCHAIN_PASSWORD $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P ${{ secrets.p12_password }} -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      # Build a production release of the Flutter project.
      - run: melos build:ios:runner
        working-directory: ${{ inputs.app-dir }}
      
      # Upload the production release to the Apple Store and make it available in TestFlight.
      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: ${{ inputs.app-dir }}/${{ inputs.app-path }}
          issuer-id: ${{ secrets.app_store_issuer_id}}
          api-key-id: ${{ secrets.app_store_api_key_id}}
          api-private-key: ${{ secrets.app_store_api_private_key}}
      
      # Ensure the installed secrets and certificates are removed from the build agent.
      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
          rm ~/Library/MobileDevice/Provisioning\ Profiles/provisioningprofile.mobileprovision
