name: Run flutter tests
on:
  workflow_call:
    inputs:
      app-dir:
        required: true
        type: string
      android_keystore_path:
        required: false
        default: 'android/upload.jks'
        type: string
      android_keystore_alias:
        required: false
        default: 'upload'
        type: string

    secrets:
      android_key_asc:
        required: true
      android_key_passphrase:
        required: true
      android_keystore_private_key_password:
        required: true
      android_keystore_password:
        required: true
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available optionsjava-version
        java-version: '17'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
      env:
        ANDROID_KEYSTORE_PATH: ${{ inputs.android_keystore_path }}
        ANDROID_KEYSTORE_ALIAS: ${{ inputs.android_keystore_alias }}
        ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.android_keystore_private_key_password }}
        ANDROID_KEYSTORE_PASSWORD: ${{ secrets.android_keystore_password }}
    - run: flutter pub get
      working-directory: ${{ inputs.app-dir }}
    - run: |
        echo "${{secrets.android_key_asc}}" > upload.keystore.asc
        gpg -d --passphrase "${{ secrets.android_key_passphrase }}" --batch upload.keystore.asc > ${{ inputs.android_keystore_path }} 
      working-directory: ${{ inputs.app-dir }}
    - run: flutter build appbundle --flavor production --dart-define "ENVIRONMENT=production"  --dart-define "API_BASE_URL=https://api.beansapp.com/v1/"  
      working-directory: ${{ inputs.app-dir }}
