name: Deploy Android
on:
  workflow_call:
    inputs:
      app-dir:
        required: true
        type: string
      android_keystore_path:
        required: true
        default: 'upload.jks'
        type: string
      android_keystore_alias:
        required: true
        default: 'upload'
        type: string
      environment: # options development|staging|production
        required: true
        type: string
      packageName: # this should be optional.. https://github.com/r0adkll/upload-google-play/issues/103
        required: true
        type: string

    secrets:
      android_key_asc:
        required: true
      android_key_passphrase:
        required: true
      android_keystore_private_key_password:
        required: false
      android_keystore_password:
        required: false
      play_store_gservice_account:
        required: true
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available optionsjava-version
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Download melos
        run: dart pub global activate melos
      - name: Melos init
        run: melos bootstrap && melos generate
      - name: Decrypt keystore
        run: |
          ls -la
          echo "${{secrets.android_key_asc}}" > upload.keystore.asc
          gpg -d --passphrase "${{ secrets.android_key_passphrase }}" --batch upload.keystore.asc > '${{inputs.app-dir}}/'${{ inputs.android_keystore_path }}
        working-directory: ${{ inputs.app-dir }}
      - name: Melos build Android Production
        run: melos build:android
      - name: Release APPBUNDLE to internal track
        uses: r0adkll/upload-google-play@v1.0.16
        with:
          serviceAccountJsonPlainText: ${{ secrets.play_store_gservice_account }}
          releaseFile: ${{inputs.app-dir}}/build/app/outputs/bundle/productionRelease/app-production-release.aab
          status: 'draft'
          track: internal
          packageName: ${{inputs.packageName}}
      - name: Clean up keychain and provisioning profile
        if: ${{ always() }}
        run: |
          security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
