name: Run flutter tests
on:
  workflow_call:
    inputs:
      username:
        app-dir: true
        type: string
    secrets:
      token:
        required: true
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
      working-directory: ${{ inputs.app-dir }}
    - run: flutter test
      working-directory: ${{ inputs.app-dir }}
    - run: flutter build ios --release --no-codesign
      working-directory: ${{ inputs.app-dir }}
