name: Run flutter tests
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  run-flutter-tests:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
    with:
      flutter-version: '2.8.0'
        channel: 'stable'
    - run: flutter --version
