name: Run flutter tests
on:
  workflow_call:
    inputs:
      app-dir:
        required: true
        type: string
    secrets:
      token:
        required: true
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        # use the build-in cache from Subosito
        cache: true
        
    - run: flutter pub get
      working-directory: ${{ inputs.app-dir }}
    - run: flutter test
      working-directory: ${{ inputs.app-dir }}
